### PR TITLE
updating main with closed actions

### PR DESCRIPTION
**Pull request by cbayley96**
I put in all our stories for testing, what do you guys think?

### CODE REVIEW

**Comment by gillestx93** [comment]
Looks good!

**Comment by esp1998** [comment]
I love it. Very nice to see it all in our main code. I would recommend making each user story look cleaner in the addition of the main. Maybe add more useful comments so we can better understand each segment of code??

**Comment by cbayley96** [comment]
I edited it so there is clearer spacing and comments for stories, @esp1998 do you think you could add in an if statement for the user to select if they want the SpongeBob character and background? I left a space in main for it

**Comment by gillestx93** [comment]
This looks great! Awesome feedback for the changes Evan

**Comment by esp1998** [comment]
yes @cbayley96 I can try and add those if statements in the main function!

**Comment by cbayley96** [comment]
@esp1998 I added in those if statements to prompt the user to select their character/background, @gillestx93 can you check over that to make sure I did it right?

**Comment by esp1998** [comment]
Oh okay. I guess I misunderstood how that was supposed to be structured. Thank you for fixing that!

**Comment by gillestx93** [comment]
That looks correct to me!

**Comment by cbayley96** [comment]
Merging with main and deleting branch for Sprint 1!

**Pull request merged**
