### PR TITLE
User Story 7 Task 11

### PR DESCRIPTION
**Pull request by cbayley96**
I added in an option to make the player select either English or Spanish for Task 11, I tried just directly taking the rules box for task 1 and translating it so I could not get it to look right, but I feel this could be a could start and if we got the main working, we could have tested it to see!

### CODE REVIEW

**Comment by esp1998** [comment]
Yes you are probably right. In theory though, would a dictionary of sorts be used within the function in the background or would the user be asked to select it?

**Comment by cbayley96** [comment]
I was thinking the user would select it, but I couldn't figure out how to implement that with the text files in making a pop up box. Any ideas?

**Comment by esp1998** [comment]
Do you think a multipage translator image would suffice?

**Comment by gillestx93** [comment]
I think this would work. But I've never tried translating anything before. I think a switch statement is a good idea for simple messages

**Comment by cbayley96** [comment]
Yeah I thought about using a switch but didn't think I really needed to since it is just a small if between two languages!

**Comment by esp1998** [comment]
Do you feel you can complete this task or would it be best to close this as is and marked as "delayed"?

**Comment by cbayley96** [comment]
yeah I think marking this as delayed would be best since I couldn't figure out how to implement the pop up box :(

**Pull request closed without merging**
