### PR TITLE
Sprint3 ep

### PR DESCRIPTION
**Pull request by esp1998**
Alright so I have 2 commits ready for a pull request review but the functions within them were very tricky even though there may not be much code. I tried researching the best way to do this task but it wasn't much of a starting place. As stated in my extended comments of my commits, this was a shot in the dark. I bit off more than I could chew. Wasn't sure if they needed to be their own functions or out inside the main.

### CODE REVIEW

**Comment by cbayley96** [comment]
I personally haven't done anything with sound in an application so I am not sure how much help I can be, but are you planning on uploading that sound clip too? I am not sure how well that works with GitHub. I think they look okay, I wish we could test them and see what happens, but I still haven't been able to figure out why the main isn't running. But to your last comment, I think we would have to add it to the main to be safe, but I feel like it could go either way.

**Comment by cbayley96** [comment]
I see you added in that clip so thank you!!! I think your functions are fine, have you thought about if you want to add them into the main or their own functions?

**Comment by esp1998** [comment]
I'm leaning towards own functions but that would only work if we could actually compile our code haha.

**Comment by gillestx93** [comment]
I don't think this necessarily needs to be its own function. I would just have it in the while loop that contains the actions that start the game

**Comment by esp1998** [comment]
Hey guys! After further consideration, it's obvious that this task needs to be delayed. This will not be able to be completed by the end of the semester. I believe this is the best option remaining.

**Comment by cbayley96** [comment]
okay that sounds good!!!! I appreciate you trying to get it done though!!

**Pull request merged**
