### PR TITLE
Sprint3 tg

### PR DESCRIPTION
**Pull request by gillestx93**
Added the image to be used for the enemy sprite 
Created a function that creates sprites and moves them randomly for the user to avoid

### CODE REVIEW

**Comment by cbayley96** [comment]
so your file names are completely different, one is .jpg and one is .png, so I would make sure to switch one of them, but other than that I think it looks good!

**Comment by esp1998** [comment]
Make sure your file extensions match like @cbayley96 said. This task seems very difficult. I'm not entirely sure what advice I can offer based on the fact I wouldn't know where to start myself.

**Comment by gillestx93** [comment]
The file name for the image has been corrected

**Comment by cbayley96** [comment]
looks good! good work Timberly!!

**Pull request merged**
