### PR TITLE
updating main

### PR DESCRIPTION
**Pull request by cbayley96**
I am updating the main with all of the User Stories (except for Sprint 3 so tasks 7-9) so we have our SDD started. With the SDD, he said in class it is best to comment out design, so I have included those! I tried running it before I added in comments, but it is not liking one of the libraries, do you think one of you two can try running it and letting me know if it is just on my end? Other than that, let me know what you think of the comments, and let me know if I should change anything or clarify anything!

### CODE REVIEW

**Comment by esp1998** [comment]
This is not a bad idea. Yes I will try compiling the main and see where I get to! I'll be specific with the type of error too.

**Comment by esp1998** [comment]
Okay so something that happens is that when I try to run it in VS code, it throws an error saying: "
Warning: Failed to watch ref 'c:\Users\cbayl\CEG-4110Project\DoodleJump.git\refs\remotes\origin\master', is most likely packed." I'm not entirely sure what this means. I'll have to look more into it and see if I can find what is causing this. Most likely errors in the function calls themselves.

**Comment by gillestx93** [comment]
Which library is it not liking? You might need to install it in your person VS to make it work

**Comment by cbayley96** [comment]
It looks like it isn't liking the windows header one, but I tried installing that through VS code again, but now I just keep getting that error Evan is getting. @gillestx93 do you know why that would be?

**Comment by cbayley96** [comment]
Are you guys good with closing this issue out? do the comments for the SDD look good to you?

**Comment by esp1998** [comment]
Yes would you like me to close this one out?

**Comment by cbayley96** [comment]
yep you can close it out since it just has our SDD!

**Pull request merged**
