### PR TITLE
Idea for User Story 4 CB

### PR DESCRIPTION
**Pull request by cbayley96**
This goes along with my user story about wanting to implement a feature for the user to save their progress, in case they want to exit the game (pulled from this site http://www.cplusplus.com/forum/general/77026/ )

### CODE REVIEW

**Comment by cbayley96** [comment]
accidentally closed, reopening request

**Comment by gillestx93** [comment]
Needs a mouse click event to determine whether the user clicked the 'X'

**Comment by esp1998** [comment]
I would make sure that the variables and parameters have more meaningful names. Ones we can agree on

**Comment by cbayley96** [comment]
I updated the variable names, still not sure how to implement the mouse click, I will look more into it another time!

**Comment by cbayley96** [comment]
I just updated the file with a pop up box, what do you guys think?

**Comment by gillestx93** [comment]
I think that looks good!

**Review by esp1998 — APPROVED** [review]
These are meaningful changes. Great work

**Pull request merged**
